server:
  port: 8010
spring:
  application:
    name: sc-user-service
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    #    localhost run
    #    url: jdbc:mysql://localhost:3306/sale_cloud?useUnicode=true&characterEncoding=UTF8&serverTimezone=Asia/Shanghai
    #    username: root
    #    password: 1234

    #   remote run
    url: jdbc:mysql://localhost:3306/sale_cloud?&useUnicode=true&characterEncoding=UTF8&serverTimezone=Asia/Shanghai
    username: root
    password: 123456
hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 2000
eureka:
  instance:
    hostname: localhost
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/