server:
  port: 8764

spring:
  application:
    name: service-turbine

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

turbine:
  aggregator:
    clusterConfig: default
  appConfig: service-client-hi,service-client-hello
  clusterNameExpression: "'default'"