spring:
  application:
    name: health-handler-provider
eureka:
  instance:
    hostname: localhost
  client:
    healthcheck: 
      enabled: true
    instanceInfoReplicationIntervalSeconds: 10
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
