server:
  port: 8763
spring:
  application:
    name: service-blog
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
swagger:
  contact:
    name: hly
    url: www.javahly.com
    email: 1136513099@qq.com