# 数据库配置
spring:
  datasource:
    name: test
    url: jdbc:mysql://${MYSQL_HOST:127.0.0.1}:${MYSQL_PORT:3306}/${MYSQL_DB:student}?useUnicode=true&characterEncoding=UTF8&serverTimezone=Asia/Shanghai
    username: root
    password: 1234
    driver-class-name: com.mysql.cj.jdbc.Driver
  # 时区和json配置
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8

# mybatis配置
mybatis:
  config-location: classpath:mybatis/mybatis-config.xml
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.wang.swagger.demo.entity

# 日志级别
logging:
  level:
    com.wang.swagger.demo: debug

## 端口号
#server:
#  port: 8080
#
## K-V
#student:
#  name: 1
#  age: 1
#
#student1: {name: q,age: 2}
#
#student2:
#  - dog
#  - big
#
#student3: [dog,big]

## 注入到实体类赋值
person:
  name: wang
  sex: 男
  age: 19
  birth: 2020/01/01 01:11:11
  map: {k1: 1,k2: 2}
  lists:
    - like
    - dislike
  happy: false
  dog:
    name: wangwang
    sex: 男


