# 数据库配置
spring:
  datasource:
    name: test
    url: jdbc:mysql://${MYSQL_HOST:127.0.0.1}:${MYSQL_PORT:3306}/${MYSQL_DB:student}?useUnicode=true&characterEncoding=UTF8&serverTimezone=Asia/Shanghai
    username: root
    password: 1234
    driver-class-name: com.mysql.cj.jdbc.Driver
  # 时区和json配置
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8

# mybatis配置
mybatis:
  config-location: classpath:mybatis/mybatis-config.xml
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.wang.swagger.demo.entity

# 日志级别
logging:
  level:
    com.wang.swagger.demo: debug
server:
  port: 8083

# 对象配置
person:
  name: 名称
  sex: 男
  age: 19
  birth: 2020/01/12
  lists:
    - 这是lists1
    - 这是lists2
    - 这是lists3
  map: {k1: v1,k2: v2}
  happy: true
  Dog:
    name: 小狗
    sex: 男


