# 端口8081
server:
  port: 8081

# 数据层配置
mybatis:
  basepackage: com.example.demo.dao
  xmlLocation: classpath:mapper/**/*.xml
  mapper-locations: "classpath:mapper/**/*.xml"

# 数据库配置
spring:
  datasource:
    url: jdbc:mysql://${MYSQL_HOST:localhost}:${MYSQL_PORT:3306}/student?useUnicode=true&characterEncoding=UTF8&serverTimezone=Asia/Shanghai
    username: root
    password: 1234
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver