# 数据库配置
spring:
  datasource:
    name: test
    url: jdbc:mysql://${MYSQL_HOST:127.0.0.1}:${MYSQL_PORT:3306}/${MYSQL_DB:student}?useUnicode=true&characterEncoding=UTF8&serverTimezone=Asia/Shanghai
    username: root
    password: 1234
    driver-class-name: com.mysql.cj.jdbc.Driver
  # 时区和json配置
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8

# mybatis配置
mybatis:
  config-location: classpath:mybatis/mybatis-config.xml
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.spring.wang.entity

# 日志级别
logging:
  level:
    com.spring.wang: DEBUG

# 配置端口
server:
  port: 8081

  # swagger config
  swagger:
    enabled: true                                  # 是否启用swagger